INSERT INTO estoque (nome, quantidade, fabricante, tipo) VALUES ('Motor Ford Duratorq TDCi', 100, 'Ford', 'Motor');
INSERT INTO estoque (nome, quantidade, fabricante, tipo) VALUES ('Motor Cummins ISF 2.8 Diesel', 50, 'Cummins', 'Motor');
INSERT INTO estoque (nome, quantidade, fabricante, tipo) VALUES ('Motor Honda L15B7', 75, 'Honda', 'Motor');
INSERT INTO estoque (nome, quantidade, fabricante, tipo) VALUES ('Motor Volkswagen EA888', 80, 'Volkswagen', 'Motor');
INSERT INTO estoque (nome, quantidade, fabricante, tipo) VALUES ('Motor Toyota 2ZR-FE', 90, 'Toyota', 'Motor');
INSERT INTO estoque (nome, quantidade, fabricante, tipo) VALUES ('Kit 5 Pneu Pirelli', 200, 'Pirelli', 'Pneu');
INSERT INTO estoque (nome, quantidade, fabricante, tipo) VALUES ('Kit 5 Pneu Bridgestone', 180, 'Bridgestone', 'Pneu');
INSERT INTO estoque (nome, quantidade, fabricante, tipo) VALUES ('Kit 5 Pneu Continental', 150, 'Continental', 'Pneu');
INSERT INTO estoque (nome, quantidade, fabricante, tipo) VALUES ('Kit 5 Pneu Michelin', 220, 'Michelin', 'Pneu');
INSERT INTO estoque (nome, quantidade, fabricante, tipo) VALUES ('Tesla', 50, 'Tesla', 'Chassi');
INSERT INTO estoque (nome, quantidade, fabricante, tipo) VALUES ('BMW', 60, 'BMW', 'Chassi');
INSERT INTO estoque (nome, quantidade, fabricante, tipo) VALUES ('Volvo', 40, 'Volvo', 'Chassi');
INSERT INTO estoque (nome, quantidade, fabricante, tipo) VALUES ('Jeep', 70, 'Jeep', 'Chassi');
INSERT INTO estoque (nome, quantidade, fabricante, tipo) VALUES ('Chevrolet', 80, 'Chevrolet', 'Chassi');
INSERT INTO estoque (nome, quantidade, fabricante, tipo) VALUES ('Toyota', 90, 'Toyota', 'Chassi');
INSERT INTO estoque (nome, quantidade, fabricante, tipo) VALUES ('Mercedes-Benz', 55, 'Mercedes-Benz', 'Chassi');